import { getDocument, GlobalWorkerOptions } from 'pdfjs-dist';
import type { TextItem } from 'pdfjs-dist/types/src/display/api';
import type { PDFPageProxy } from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.mjs?url';

GlobalWorkerOptions.workerSrc = workerUrl;

interface PageResult {
  lines: string[];
}

interface ReadPdfParams {
  data: ArrayBuffer;
  password?: string;
  progressCallback?: (progress: { loaded: number; total: number }) => void;
  options?: Record<string, unknown>;
}

/** Reads a PDF into a single string. */
export async function readPdfText(params: ReadPdfParams): Promise<string> {
  const pdfPages = await readPdfPages(params);
  return combinePagesIntoSingleString(pdfPages);
}

/** Combine all PDF pages into a single string. */
export function combinePagesIntoSingleString(pages: PageResult[]): string {
  return pages
    .map((page) => page.lines)
    .flat()
    .join('\n');
}

/** Parse a single PDF page. */
export async function parsePage(pdfPage: PDFPageProxy): Promise<PageResult> {
  const rawContent = await pdfPage.getTextContent();
  return parsePageItems(rawContent.items.filter((item): item is TextItem => 'str' in item));
}

/**
 * Read a PDF and convert it into lines of text.
 */
export async function readPdfPages({ data, password, progressCallback, options }: ReadPdfParams): Promise<PageResult[]> {
  const documentLoadingTask = getDocument({
    data,
    password,
    useSystemFonts: true,
    ...options,
  });
  if (progressCallback) documentLoadingTask.onProgress = progressCallback;

  const pdfDoc = await documentLoadingTask.promise;
  const pageCount = pdfDoc.numPages;
  const pages: PageResult[] = [];
  for (let i = 0; i < pageCount; i++) {
    const page = await pdfDoc.getPage(i + 1);
    pages.push(await parsePage(page));
  }

  return pages;
}

/**
 * Parses individual text items generated by pdf.js.
 */
export function parsePageItems(pdfItems: TextItem[]): PageResult {
  const lineData: Record<number, TextItem[]> = {};

  for (let i = 0; i < pdfItems.length; i++) {
    const item = pdfItems[i];
    const y = item.transform[5];
    if (!(y in lineData)) {
      lineData[y] = [];
    }
    lineData[y].push(item);
  }

  const yCoords = Object.keys(lineData)
    .map((key) => Number(key))
    .sort((a, b) => b - a)
    .reduce<number[]>((accum, currentY, index, array) => {
      const nextY = array[index + 1];
      if (nextY !== undefined) {
        const currentLine = lineData[currentY];
        const currentLineHeight = currentLine.reduce(
          (finalValue, current) => (finalValue > current.height ? finalValue : current.height),
          -1
        );

        if (Math.floor((currentY - nextY) / currentLineHeight) > 1) {
          const newY = currentY - currentLineHeight;
          lineData[newY] = [];
          return accum.concat(currentY, newY);
        }
      }
      return accum.concat(currentY);
    }, []);

  const lines: string[] = [];
  for (let i = 0; i < yCoords.length; i++) {
    const y = yCoords[i];
    if (y === undefined) continue;

    const lineItems = lineData[y]
      .sort((a, b) => a.transform[4] - b.transform[4])
      .filter((item) => !!item.str);
    const firstLineItem = lineItems[0];
    let line = lineItems.length ? firstLineItem.str : '';
    for (let j = 1; j < lineItems.length; j++) {
      const item = lineItems[j];
      const lastItem = lineItems[j - 1];
      const xDiff = item.transform[4] - (lastItem.transform[4] + lastItem.width);

      if (item.height !== 0 && lastItem.height !== 0 && (xDiff > item.height || xDiff > lastItem.height)) {
        const spaceCountA = Math.ceil(xDiff / item.height);
        let spaceCount = spaceCountA;
        if (lastItem.height !== item.height) {
          const spaceCountB = Math.ceil(xDiff / lastItem.height);
          spaceCount = spaceCountA > spaceCountB ? spaceCountA : spaceCountB;
        }
        line += Array(spaceCount).fill('').join(' ');
      }
      line += item.str;
    }
    lines.push(line);
  }

  return { lines };
}
